#!/usr/bin/env bash

# Creates desktop entries for AppImages on specified directories
# Not as feature-rich as AppImageLauncer, but serves its purpose well to create desktop entries of AppImages


require() {
    command -v $1 &>/dev/null || { >&2 echo "$1 is required, and not present, exiting..."; exit 1; }
}
require inotifywait
require fd

# runs mkdir while inheriting the owner by looking at nearest parent dir that existed
inherited_mkdir() {
    local nearest_non_existent=$(while read -rd '/' c && cd "$c" 2>/dev/null; do :; done <<< "$1"; echo $PWD/$c)
    local nearest_parent=$(dirname "$nearest_non_existent")
    local nearest_parent_owner=$(stat -c "%U:%G" "$nearest_parent")

    mkdir -p "$1"
    chown -R $nearest_parent_owner $nearest_non_existent
}

# create or check entry for file exists & matches
create_entry() {
    echo "cr $1"

    local desktop_entry_dir=/usr/share/applications
    local desktop_icons_dir=/usr/share/icons
    mkdir -p $desktop_entry_dir
    mkdir -p $desktop_icons_dir


}

# delete entry for file
remove_entry() {
    echo "rm $1"
}


CONF_FILE=/etc/appimage-desktop.conf
recursive_opt=
depth_opt=
watch_paths=

if [[ ! -r $CONF_FILE ]]; then
    >&2 echo "$CONF_FILE does not exist or is not readable"
    exit 2
fi

while read -r line; do
    case "$line" in
        recursive=true)
            recursive_opt=-r
            depth_opt=;;
        recursive=*)
            recursive_opt=
            depth_opt=-d1;;
        '')
            continue;;
        *)
            if [[ ! -d "$line" ]] && ! inherited_mkdir "$line"; then
                >&2 echo "File $line exists but not a directory"
                exit 3
            fi
            watch_paths="$watch_paths $line";;
    esac
done < $CONF_FILE


# Listen & create/remove entry
inotifywait -e create -e moved_to --include '.*\.AppImage' $recursive_opt -m $watch_paths 2>/dev/null \
| while read dir action file; do
    create_entry "$dir$file"
done &

inotifywait -e delete -e moved_from --include '.*\.AppImage' $recursive_opt -m $watch_paths 2>/dev/null \
| while read dir action file; do
    remove_entry "$dir$file"
done &


# Create/check entry for all at start
for path in $watch_paths; do
    fd --absolute-path $depth_opt '.' "$path" \
    | while read -r file; do
        create_entry "$file"
    done
done


trap 'kill $(jobs -p)' EXIT

# Exit as soon as any child process returns with non-zero exit code
while [[ -n $(jobs -p) ]]; do
     if ! wait -n < <(jobs -p); then
         exit 1
     fi
done
